-- Test data to be inserted into embedded database

CREATE TABLE "SEQUENCE"(
    "SEQUENCE_NAME" VARCHAR(50) PRIMARY KEY NOT NULL,
    "VALUE" INT
);

CREATE TABLE PATIENT(
    ID INT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);
CREATE TABLE CONTACT_INFO(
    ID INT PRIMARY KEY NOT NULL,
    PHONE_NUMBER VARCHAR(10),
    EMAIL VARCHAR(50)
);
CREATE TABLE ADDRESS(
    ID INT PRIMARY KEY NOT NULL,
    STREET VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP VARCHAR(5),
    COUNTRY VARCHAR(50)
);

INSERT INTO SEQUENCE (SEQUENCE_NAME, VALUE) VALUES(
    'PATIENT_SEQUENCE',
    6
);
INSERT INTO SEQUENCE (SEQUENCE_NAME, VALUE) VALUES(
    'CONTACT_INFO_SEQUENCE',
    1
);
INSERT INTO SEQUENCE (SEQUENCE_NAME, VALUE) VALUES(
    'ADDRESS_SEQUENCE',
    1
);

-- Patient List
INSERT INTO PATIENT (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES (1, 'Jacob', 'Anthony', 'DOnofrio');
INSERT INTO PATIENT (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES (2, 'Katelyn', 'Marie', 'DOnofrio');
INSERT INTO PATIENT (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES (3, 'Brandon', NULL, 'Baratono');
INSERT INTO PATIENT (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES (4, 'Rachel', NULL, 'Baratono');
INSERT INTO PATIENT (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES (5, 'Grady', NULL, 'Bolte');